### ISSUE TITLE
AdomdConnection

### ISSUE THREAD

**Issue by acasterm** [S-C-O-U-T/Pyadomd#1]
When I try to instantiate the Pyadomd object on __init__, I get the error below:

"File 'C:\my_path\pyadomd.py', line 125, in __init__ 
"self.conn = AdomdConnection()"
"Name error: name 'AdomdConnection' is not defined". 

I add the DLL to my path as specified in the README.md

I am able to successfully run the code below successfully in my interpreter with the AdomdConnection object:
>>> from pyadomd import *
>>> clr.AddReference('Microsoft.AnalysisServices.AdomdClient')
>>>from Microsoft.AnalysisServices.AdomdClient import AdomdConnection, AdomdCommand 
>>> adoObj = AdomdConnection()
>>> adoObj.ConnectionString = 'my_connection_string'
>>> adoObj.Open()
>>>print(adoObj.State)
>>>1

**Comment by S-C-O-U-T** [comment]
Which python version and AdomdClient dll are you using?

I’m not able to reproduce the error, could you post the code that produces the error?

**Comment by acasterm** [comment]
Using python 3.7.4, Microsoft.AnalysisServices.AdomdClient.dll file version: 12.0.2000.8. 

Screenshot below

![Adomd](https://user-images.githubusercontent.com/12787732/80328650-ec61b480-880d-11ea-8dcf-82e20bb8af8a.PNG)

**Comment by S-C-O-U-T** [comment]
It’s looks like it is the order of which you add the ADOMD dll to your path and initialize it. The package is looking up the ADOMD dll during import. That’s why you’re getting the error right after the import.
Try to first to add the dll to the path, such that your code looks like this:

`dll = 'C:\\\Program Files\\\Microsoft.NET\\\ADOMD.NET\\\120`
`from sys import path`
`path.append(dll)`

and afterwords import the package

`from pyadomd import Pyadomd`

**Comment by S-C-O-U-T** [comment]
Did above solve the problem? 😊

**Comment by forceair** [comment]
> It’s looks like it is the order of which you add the ADOMD dll to your path and initialize it. The package is looking up the ADOMD dll during import. That’s why you’re getting the error right after the import. Try to first to add the dll to the path, such that your code looks like this:
> 
> `dll = 'C:\\Program Files\\Microsoft.NET\\ADOMD.NET\\120` `from sys import path` `path.append(dll)`
> 
> and afterwords import the package
> 
> `from pyadomd import Pyadomd`

thank you this method is cool!
