### ISSUE TITLE
DllNotFoundException: security.dll

### ISSUE THREAD

**Issue by IcToxi** [S-C-O-U-T/Pyadomd#2]
Hi,

When I tried to access Analysis Services on Centos, I encountered DllNotFoundException: security.dll exception.

And copying this dll from Windows also doesn't work.

```
from sys import path
path.append('/usr/local/bin/') # which is dll files path

import pandas as pd
from pyadomd import Pyadomd

conn_str = "Provider=MSOLAP;DataSource=xxx.xxx;Catalog=xx;Integrated Security=SSPI;Persist Security Info=True;User ID=xxx;Password=***;"
query = '''

MDX Scripts...

'''

with Pyadomd(conn_str) as conn:
    with conn.cursor().execute(query) as cur:
        df = pd.DataFrame(cur.fetchone(),
                          columns=[i.name for i in cur.description])
```

Do you have any ideas?

**Comment by S-C-O-U-T** [comment]
Which operating system and python version are you using?

At which line do you get the exception?
•	When you import the Pyadomd package?
•	When you querying the Analysis Service Cube?

**Comment by IcToxi** [comment]
Hi,
I think I know what I'm doing, and I've also tried to use pythonnet directly, as well as installing .net runtime.
The system version is Centos 7 and python is 3.7. But I don't think this is a problem specific to a particular version.
It looks like my Centos are missing a series of components from Windows security validation, but I don't know how to import, copying DLLs directly from Windows doesn't work, and I can't find similar issues on sites like StackOverFlow, so I'd like to ask if you've studied this.

**Comment by S-C-O-U-T** [comment]
I’ve only tested it on windows.

My plan is to test if I can get to work on UNIX-like system by using Mono https://www.mono-project.com/ but I haven’t got to it yet. Pythonnet should work with the Mono runtime, so hopefully it could also be possible to get Pyadomd to do so.

**Comment by IcToxi** [comment]
Thank  you very much, I don't know much about C#. 

I've seen Mono run as a dependency library, just I'm stuck in Windows authentication.

I hope your plan will succeed.
