### ISSUE TITLE
Error System.UInt64

### ISSUE THREAD

**Issue by sorenhakola** [S-C-O-U-T/Pyadomd#5]
Hi, 

Thanks for developing this module for Python! Working fine so far, except for one thing.

When querying a DMV inside a Power BI report, I got an error pointing to data type problems. Turned out that a mapping was missing in _type_code.py.

Found a solution by adding the following line to _type_code.py
`'System.UInt64': Type_code(partial(_option_type, int), int.__name__),`

There might - of course - be others data types missing too, but this was the one that I came across. 

Br,
Sören

**Comment by S-C-O-U-T** [comment]
Thx for raising this incident, I have created a new release. Please install it with `pip install pyadomd --upgrade`
