### ISSUE TITLE
type mapping issue  for 'System.Guid', 'System.UInt32', 'System.Int16 etc

### ISSUE THREAD

**Issue by zsombor-egyed-trax** [S-C-O-U-T/Pyadomd#8]
I got key_error for 'System.Guid', 'System.UInt32', 'System.Int16 etc

please add these lines to here: https://github.com/S-C-O-U-T/Pyadomd/blob/master/pyadomd/_type_code.py#L43
```
'System.Guid': Type_code(partial(_option_type, str), str.__name__),
'System.UInt32': Type_code(partial(_option_type, int), int.__name__),
'System.Int16': Type_code(partial(_option_type, int), int.__name__),
'System.Int32':  Type_code(partial(_option_type, int), int.__name__),
```

**Comment by zsombor-egyed-trax** [comment]
![image](https://user-images.githubusercontent.com/79918210/131535706-ad666100-da88-4a72-a5bb-8d831fc2554c.png)

**Comment by S-C-O-U-T** [comment]
Thanks for the PR – looks good.

Which backend did produce these data types? (Power BI, Azure Analysis Service, SSAS Tabular, SSAS multidimensional)

**Comment by zsombor-egyed-trax** [comment]
Power BI

**Comment by S-C-O-U-T** [comment]
New package release to PyPi - closing the incedent
